/* WIFIRE S1500.NBN */

#define BOARD_PID		"WIFIRENBN"
#define BOARD_NAME		"WIFIRENBN"
#define BOARD_DESC		"WiFire NBN.S1500"
#define BOARD_VENDOR_NAME	"WiFire"
#define BOARD_VENDOR_URL	"https://www.wifire.ru"
#define BOARD_MODEL_URL		"https://wikidevi.wi-cat.ru/WiFire_S1500.NBN"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	7
#define BOARD_GPIO_BTN_WPS	18
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_SW2G	28
#define BOARD_GPIO_LED_SW5G	32
#define BOARD_GPIO_LED_POWER	30
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	29
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	0
#define BOARD_USB_PORT_SWAP	0
